#EIGEN3
FIND_PACKAGE(Eigen3 QUIET REQUIRED)
IF(EIGEN3_FOUND)
  MESSAGE(STATUS "Found EIGEN3 @ ${EIGEN3_INCLUDE_DIR}")
  INCLUDE_DIRECTORIES(${EIGEN3_INCLUDE_DIR})
ELSE(EIGEN3_FOUND)
  MESSAGE(SEND_ERROR "Cannot find Eigen3!")
ENDIF(EIGEN3_FOUND)
